# Generated by Django 5.0.2 on 2024-03-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_equipo_options_alter_goleador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoZonaDos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
